spring:
  application:
    name: Chatbot

  datasource:
    url: jdbc:postgresql://localhost:5433/Chatbotdb
    username: postgres
    password: adrian123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

    whatsapp:
      token: SEU_TOKEN_DA_META
      phone-number-id: 123456789
      verify-token: chatbot_verify

